# Generated by Django 4.0 on 2023-05-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='smlAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
                ('avg_buy_price', models.FloatField()),
                ('unit_currency', models.CharField(max_length=5)),
            ],
        ),
    ]
