# Generated by Django 4.0 on 2023-08-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_trade', '0004_alter_history_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=20)),
            ],
        ),
    ]
