# Generated by Django 4.0 on 2023-08-25 17:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_trade', '0005_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avg_buy_price',
            field=models.DecimalField(decimal_places=20, default=Decimal('0.0'), max_digits=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=20, default=Decimal('0.0'), max_digits=40),
        ),
    ]
