from django.db import models


class Ticker(models.Model):
    type = models.CharField(default='', max_length=10)
    code = models.CharField(default='', max_length=10)
    name = models.CharField(default='', max_length=20)
    opening_price = models.FloatField()
    high_price = models.FloatField()
    low_price = models.FloatField()	 
    trade_price = models.FloatField() 
    prev_closing_price = models.FloatField() 
    change = models.CharField(max_length=4)
    change_price = models.FloatField() 
    signed_change_price = models.FloatField()	 
    change_rate = models.DecimalField(max_digits=20, decimal_places=10)
    signed_change_rate = models.DecimalField(max_digits=20, decimal_places=10)
    trade_volume = models.FloatField()	 
    acc_trade_volume = models.FloatField()	 
    acc_trade_volume_24h = models.FloatField()	  
    acc_trade_price = models.FloatField()	 
    acc_trade_price_24h	= models.FloatField(null=True)
    trade_date = models.CharField(max_length=8)	 
    trade_time = models.CharField(max_length=6)	 
    trade_timestamp = models.BigIntegerField()
    ask_bid = models.CharField(default='', max_length=3)
    acc_ask_volume = models.FloatField(null=True)  	
    acc_bid_volume = models.FloatField(null=True) 	 
    highest_52_week_price = models.FloatField() 	 
    highest_52_week_date = models.CharField(max_length=10)	
    lowest_52_week_price = models.FloatField()  	 
    lowest_52_week_date = models.CharField(max_length=10)	 
    market_state = models.CharField(default='', max_length=12)	 
    is_trading_suspended = models.BooleanField(null=True)
    delisting_date = models.CharField(null=True, max_length=12)
    market_warning = models.CharField(default='', max_length=7)
    timestamp = models.BigIntegerField()
    stream_type = models.CharField(default='', max_length=8)