from django.db import models


class Ticker(models.Model):
    market = models.CharField(max_length=10)
    trade_date = models.CharField(max_length=8)
    trade_time = models.CharField(max_length=6)
    trade_date_kst = models.CharField(max_length=8)
    trade_time_kst = models.CharField(max_length=6)
    trade_timestamp = models.IntegerField()
    opening_price = models.FloatField()
    high_price = models.FloatField()
    low_price = models.FloatField()
    trade_price = models.FloatField()
    prev_closing_price = models.FloatField()
    change = models.CharField(max_length=4)
    change_price = models.FloatField()
    change_rate = models.FloatField()
    signed_change_price = models.FloatField()
    signed_change_rate = models.FloatField()
    trade_volume = models.FloatField()
    acc_trade_price = models.FloatField()
    acc_trade_price_24h = models.FloatField()
    acc_trade_volume = models.FloatField()
    acc_trade_volume_24h = models.FloatField()
    highest_52_week_price = models.FloatField()
    highest_52_week_date = models.CharField(max_length=8)
    lowest_52_week_price = models.FloatField()
    lowest_52_week_date = models.CharField(max_length=8)
    timestamp = models.FloatField()