# Generated by Django 4.0 on 2023-05-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_acc_trade_price_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
