# Generated by Django 4.0 on 2023-06-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0005_ticker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='trade_timestamp',
            field=models.BigIntegerField(),
        ),
    ]
