# Generated by Django 4.0 on 2023-06-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0006_alter_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='market_state',
            field=models.CharField(default='', max_length=12),
        ),
    ]
