# Generated by Django 4.0 on 2023-07-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0007_alter_market_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='change_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='signed_change_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
